### Get all faculties
GET   http://localhost:5000/api/v1/faculties
Content-Type: application/json

### Get single faculty  by id
GET   http://localhost:5000/api/v1/F-00001


### update faculty
POST   http://localhost:5000/api/v1/F-0001
Content-Type: application/json

{
    "name":{
        "lastName":"buddu"
    },
    "contactNo":"093"
}