


### Create User as Student
POST   http://localhost:5000/api/v1/users/create-student
Content-Type: application/json

{
    "password": "123456",     

    "student": {
        "name": {
            "firstName": "Aappa",
            "lastName": "Saha",
            "middleName": "Bapi"
        },
        "dateOfBirth": "24-04-1998",
        "gender": "male",
        "bloodGroup": "O+",
        "email": "user@gmail.com",
        "contactNo": "user_4",
        "emergencyContactNo": "01600000000",
        "presentAddress": "CTG",
        "permanentAddress": "CTG",
        "academicFaculty": "64f76b5cd726c9b3f02ba434",
        "academicDepartment": "64f76cdfd726c9b3f02ba444",
        "academicSemester": "649085178e1f4ac4cb069c0e",
        "guardian": {
            "fatherName": "MD.ABBU",
            "fatherOccupation": "Retired Teacher",
            "fatherContactNo": "01600000000",
            "motherName": "Mrs.Ammu",
            "motherOccupation": "Housewife",
            "motherContactNo": "01600000000",
            "address": "CTG"
        },
        "localGuardian": {
            "name": "Zahid Hasan",
            "occupation": "Service Holder",
            "contactNo": "01600000000",
            "address": "Dhaka"
        }

      }
}



